name: CI Backend
on:
  push:
    branches: main
    paths:
      - ".github/workflows/ci_backend.yaml"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  Lint:
    name: Check the source code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-      
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: Prettier
        run: npm run format:check
        working-directory: ${{ env.working-directory }}
      - name: Lint
        run: npm run lint
        working-directory: ${{ env.working-directory }}
  Build:
    name: Run Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      working-directory: ./backend
      mongodb-url: ${{ secrets.DATABASE_URL || 'localhost:27017' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Stack
        run: |
          docker-compose -f ./docker/docker-compose.yml up --build -d mongo
          docker ps -a
        working-directory: ${{ env.working-directory }}

      # 키 치환 하는 방식
      - name: Replace environment variables in .env.development
        run: |
          sed -i 's/^DATABASE_URL=.*/DATABASE_URL=${{ env.mongodb-url }}/g' .env.development
        working-directory: ${{ env.working-directory }}  

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ${{ env.working-directory }}

      - name: Test
        run: npm test
        working-directory: ${{ env.working-directory }}

      - name: Run build
        run: npm run build
        working-directory: ${{ env.working-directory }}  
